name: Frontend CI

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**' 

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install Dependencies
        run: |
          cd frontend
          npm install

      - name: Run Build Check
        run: |
          cd frontend
          npm run build